services:
  app:
    build:
      context: .
    depends_on:
    command: ["go", "run", "cmd/main.go", "-postgres=false"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  postgres-data:
